using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    #region ФГИЏХЭ РЬЕП
    public float x, v;
    public float speed = 5;
    Vector3 move;

    void Start()
    {
        
    }
    

    void Update()
    {
        x = Input.GetAxis("Horizontal");
        v = Input.GetAxis("Vertical");

        Vector3 move = new Vector3(x, 0, v);

        transform.position += move * speed * Time.deltaTime;  // p + p0 + vt
    }
    #endregion

    #region УбОЫ ЙпЛч 

    GameObject bulletprefab;
    GameObject fireposition; 




    void start()
    {

    }





void update()
    {
        // ИЖПьНК СТХЌИЏРЛ ДЉИІЖЇ УбОЫРЬ Л§МКЕШДй
        if(Input.GetMouseButton(0))
        {
            GameObject bullet = Instantiate(bulletprefab);
            // УбОЫРЬ firepositionРЧ РЇФЁЗЮ РЬЕПЧбДй.
            fireposition.transform.position = bullet.transform.position;
            // fire ЦїСіМЧРЧ РЇФЁДТ playerРЧ РЇПЁ РЇФЁЧиРжДй

            Vector3 firepos = new Vector3(0, 1f, 0);

            firepos = bullet.transform.position;



        }
        #endregion
    }







}